# Generated by Django 3.2.3 on 2021-06-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210621_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='language',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='uz_full_name',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
